### ISSUE TITLE
No ability to get states array

### ISSUE THREAD

**Issue by phillipsnick** [yohang/Finite#110]
I currently use this library with Symfony and define some properties for each state. But it's impossible to access these.

```yaml
finite_finite:
    product:
        class: StoreBundle\Entity\Product
        states:
            draft:
                type: initial
                properties:
                    label: 'Draft'
                    colour: 'c6c6c6' # Grey
            live:
                properties:
                    label: 'Live'
                    colour: '428bca' # Blue
            successful:
                properties:
                    label: 'Successful'
                    colour: '45B6AF' # Green
            archived:
                type: final
                properties:
                    label: 'Archived'
                    colour: '000000' # Black
        transitions:
            ...
```

Controller code:

```php
$sm = $this->get('finite.factory')->get($product);
```

Without access to this I'd have to define all my states twice, which would only make maintenance more difficult.

I previously added a bit of a hack in to get round this as I was in a hurry: https://github.com/phillipsnick/Finite/commit/477f9ba152f3c6e837e1b7c093ea12bbcd39f4ab

Is there any reason why this isn't accessible?
