### ISSUE TITLE
Add class option to states definition

### ISSUE THREAD

**Issue by tlfbrito** [yohang/Finite#27]
Can we add the class node as optional to instantiate a custom State object in the states definition?

Example:

``` yaml
finite_finite:
    my_flow:
        class: Acme\DemoBundle\Model\MyStatefulClass
        states:
            101: # Cart 1x1 Created
                class: /MySpecial/StateClass # This must implement StateInterface
                type:  initial
                properties:
                    description: Cart is open.
                    cart: true
            201: # Order 2x1 Created
                class: /MySpecial/StateClass # This must implement StateInterface
                type:  normal
                properties:
                    description: Order has started.
                    order: true
```
