### ISSUE TITLE
Override/Add transitions

### ISSUE THREAD

**Issue by kayue** [yohang/Finite#52]
Similar to #40, currently it is not possible to add new transitions to an existing graph.
However `states` is able to extend from pervious config.

Another question, when I try to extend an existing graph, I must define `class`, `property_path` and `graph` again. Is this an expected behaviour?

``` yml
finite_finite:
    sylius_order_shipping:
        class:         %sylius.model.order.class%
        property_path: shippingState
        graph:         sylius_order_shipping
```

ping @winzou
